// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// coarse_grain
NumericMatrix coarse_grain(NumericMatrix mat, int subsize);
RcppExport SEXP spatialwarnings_coarse_grain(SEXP matSEXP, SEXP subsizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type subsize(subsizeSEXP);
    rcpp_result_gen = Rcpp::wrap(coarse_grain(mat, subsize));
    return rcpp_result_gen;
END_RCPP
}
// discpowerexp_norm
double discpowerexp_norm(double expo, double rate, int xmin);
RcppExport SEXP spatialwarnings_discpowerexp_norm(SEXP expoSEXP, SEXP rateSEXP, SEXP xminSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type expo(expoSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< int >::type xmin(xminSEXP);
    rcpp_result_gen = Rcpp::wrap(discpowerexp_norm(expo, rate, xmin));
    return rcpp_result_gen;
END_RCPP
}
// label
IntegerMatrix label(IntegerMatrix mat, IntegerMatrix nbmask, bool wrap);
RcppExport SEXP spatialwarnings_label(SEXP matSEXP, SEXP nbmaskSEXP, SEXP wrapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type nbmask(nbmaskSEXP);
    Rcpp::traits::input_parameter< bool >::type wrap(wrapSEXP);
    rcpp_result_gen = Rcpp::wrap(label(mat, nbmask, wrap));
    return rcpp_result_gen;
END_RCPP
}
// raw_moran
double raw_moran(NumericMatrix mat);
RcppExport SEXP spatialwarnings_raw_moran(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(raw_moran(mat));
    return rcpp_result_gen;
END_RCPP
}
// tplsum
NumericVector tplsum(double expo, double rate, IntegerVector xs);
RcppExport SEXP spatialwarnings_tplsum(SEXP expoSEXP, SEXP rateSEXP, SEXP xsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type expo(expoSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type xs(xsSEXP);
    rcpp_result_gen = Rcpp::wrap(tplsum(expo, rate, xs));
    return rcpp_result_gen;
END_RCPP
}
// rspectrum
DataFrame rspectrum(NumericMatrix rmat);
RcppExport SEXP spatialwarnings_rspectrum(SEXP rmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type rmat(rmatSEXP);
    rcpp_result_gen = Rcpp::wrap(rspectrum(rmat));
    return rcpp_result_gen;
END_RCPP
}
// sum_all_one_over_k
double sum_all_one_over_k(int from, int to, double expo);
RcppExport SEXP spatialwarnings_sum_all_one_over_k(SEXP fromSEXP, SEXP toSEXP, SEXP expoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    Rcpp::traits::input_parameter< double >::type expo(expoSEXP);
    rcpp_result_gen = Rcpp::wrap(sum_all_one_over_k(from, to, expo));
    return rcpp_result_gen;
END_RCPP
}
// sum_all_one_over_k_before
double sum_all_one_over_k_before(int n, double expo);
RcppExport SEXP spatialwarnings_sum_all_one_over_k_before(SEXP nSEXP, SEXP expoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type expo(expoSEXP);
    rcpp_result_gen = Rcpp::wrap(sum_all_one_over_k_before(n, expo));
    return rcpp_result_gen;
END_RCPP
}
