// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// coarse_grain
NumericMatrix coarse_grain(NumericMatrix mat, int subsize);
RcppExport SEXP spatialwarnings_coarse_grain(SEXP matSEXP, SEXP subsizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type subsize(subsizeSEXP);
    __result = Rcpp::wrap(coarse_grain(mat, subsize));
    return __result;
END_RCPP
}
// get_nb_coords
IntegerMatrix get_nb_coords(IntegerMatrix mat, IntegerVector X, IntegerMatrix nbmask, bool wrap);
RcppExport SEXP spatialwarnings_get_nb_coords(SEXP matSEXP, SEXP XSEXP, SEXP nbmaskSEXP, SEXP wrapSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type nbmask(nbmaskSEXP);
    Rcpp::traits::input_parameter< bool >::type wrap(wrapSEXP);
    __result = Rcpp::wrap(get_nb_coords(mat, X, nbmask, wrap));
    return __result;
END_RCPP
}
// get_nb_values
IntegerVector get_nb_values(IntegerMatrix mat, IntegerVector X, IntegerMatrix nbmask, bool wrap);
RcppExport SEXP spatialwarnings_get_nb_values(SEXP matSEXP, SEXP XSEXP, SEXP nbmaskSEXP, SEXP wrapSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type nbmask(nbmaskSEXP);
    Rcpp::traits::input_parameter< bool >::type wrap(wrapSEXP);
    __result = Rcpp::wrap(get_nb_values(mat, X, nbmask, wrap));
    return __result;
END_RCPP
}
// label
IntegerMatrix label(IntegerMatrix mat, IntegerMatrix nbmask, bool wrap);
RcppExport SEXP spatialwarnings_label(SEXP matSEXP, SEXP nbmaskSEXP, SEXP wrapSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type nbmask(nbmaskSEXP);
    Rcpp::traits::input_parameter< bool >::type wrap(wrapSEXP);
    __result = Rcpp::wrap(label(mat, nbmask, wrap));
    return __result;
END_RCPP
}
// raw_moran
double raw_moran(NumericMatrix mat);
RcppExport SEXP spatialwarnings_raw_moran(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    __result = Rcpp::wrap(raw_moran(mat));
    return __result;
END_RCPP
}
// myfftshift
ComplexMatrix myfftshift(ComplexMatrix mat);
RcppExport SEXP spatialwarnings_myfftshift(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< ComplexMatrix >::type mat(matSEXP);
    __result = Rcpp::wrap(myfftshift(mat));
    return __result;
END_RCPP
}
// normalize
NumericMatrix normalize(NumericMatrix aspectr2D, NumericMatrix dists, int n0x, int n0y);
RcppExport SEXP spatialwarnings_normalize(SEXP aspectr2DSEXP, SEXP distsSEXP, SEXP n0xSEXP, SEXP n0ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type aspectr2D(aspectr2DSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dists(distsSEXP);
    Rcpp::traits::input_parameter< int >::type n0x(n0xSEXP);
    Rcpp::traits::input_parameter< int >::type n0y(n0ySEXP);
    __result = Rcpp::wrap(normalize(aspectr2D, dists, n0x, n0y));
    return __result;
END_RCPP
}
// get_distances
NumericMatrix get_distances(int nr, int nc, int n0x, int n0y);
RcppExport SEXP spatialwarnings_get_distances(SEXP nrSEXP, SEXP ncSEXP, SEXP n0xSEXP, SEXP n0ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type nr(nrSEXP);
    Rcpp::traits::input_parameter< int >::type nc(ncSEXP);
    Rcpp::traits::input_parameter< int >::type n0x(n0xSEXP);
    Rcpp::traits::input_parameter< int >::type n0y(n0ySEXP);
    __result = Rcpp::wrap(get_distances(nr, nc, n0x, n0y));
    return __result;
END_RCPP
}
// get_rspectr
NumericVector get_rspectr(NumericVector ray, double step, NumericMatrix dists, NumericMatrix aspectr2D);
RcppExport SEXP spatialwarnings_get_rspectr(SEXP raySEXP, SEXP stepSEXP, SEXP distsSEXP, SEXP aspectr2DSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type ray(raySEXP);
    Rcpp::traits::input_parameter< double >::type step(stepSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dists(distsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type aspectr2D(aspectr2DSEXP);
    __result = Rcpp::wrap(get_rspectr(ray, step, dists, aspectr2D));
    return __result;
END_RCPP
}
