// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// coarse_grain
NumericMatrix coarse_grain(NumericMatrix mat, int subsize);
RcppExport SEXP spatialwarnings_coarse_grain(SEXP matSEXP, SEXP subsizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type subsize(subsizeSEXP);
    __result = Rcpp::wrap(coarse_grain(mat, subsize));
    return __result;
END_RCPP
}
// get_nb_coords
IntegerMatrix get_nb_coords(IntegerMatrix mat, IntegerVector X, IntegerMatrix nbmask, bool wrap);
RcppExport SEXP spatialwarnings_get_nb_coords(SEXP matSEXP, SEXP XSEXP, SEXP nbmaskSEXP, SEXP wrapSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type nbmask(nbmaskSEXP);
    Rcpp::traits::input_parameter< bool >::type wrap(wrapSEXP);
    __result = Rcpp::wrap(get_nb_coords(mat, X, nbmask, wrap));
    return __result;
END_RCPP
}
// get_nb_values
IntegerVector get_nb_values(IntegerMatrix mat, IntegerVector X, IntegerMatrix nbmask, bool wrap);
RcppExport SEXP spatialwarnings_get_nb_values(SEXP matSEXP, SEXP XSEXP, SEXP nbmaskSEXP, SEXP wrapSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type nbmask(nbmaskSEXP);
    Rcpp::traits::input_parameter< bool >::type wrap(wrapSEXP);
    __result = Rcpp::wrap(get_nb_values(mat, X, nbmask, wrap));
    return __result;
END_RCPP
}
// label
IntegerMatrix label(IntegerMatrix mat, IntegerMatrix nbmask, bool wrap);
RcppExport SEXP spatialwarnings_label(SEXP matSEXP, SEXP nbmaskSEXP, SEXP wrapSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type nbmask(nbmaskSEXP);
    Rcpp::traits::input_parameter< bool >::type wrap(wrapSEXP);
    __result = Rcpp::wrap(label(mat, nbmask, wrap));
    return __result;
END_RCPP
}
// raw_moran
double raw_moran(NumericMatrix mat);
RcppExport SEXP spatialwarnings_raw_moran(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    __result = Rcpp::wrap(raw_moran(mat));
    return __result;
END_RCPP
}
// rspectrum
DataFrame rspectrum(NumericMatrix rmat);
RcppExport SEXP spatialwarnings_rspectrum(SEXP rmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type rmat(rmatSEXP);
    __result = Rcpp::wrap(rspectrum(rmat));
    return __result;
END_RCPP
}
