# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coarse_grain <- function(mat, subsize) {
    .Call('spatialwarnings_coarse_grain', PACKAGE = 'spatialwarnings', mat, subsize)
}

.get_nb_coords <- function(mat, X, nbmask, wrap) {
    .Call('spatialwarnings_get_nb_coords', PACKAGE = 'spatialwarnings', mat, X, nbmask, wrap)
}

.get_nb_values <- function(mat, X, nbmask, wrap) {
    .Call('spatialwarnings_get_nb_values', PACKAGE = 'spatialwarnings', mat, X, nbmask, wrap)
}

.label <- function(mat, nbmask, wrap) {
    .Call('spatialwarnings_label', PACKAGE = 'spatialwarnings', mat, nbmask, wrap)
}

#' @export
raw_moran <- function(mat) {
    .Call('spatialwarnings_raw_moran', PACKAGE = 'spatialwarnings', mat)
}

.myfftshift_cpp <- function(mat) {
    .Call('spatialwarnings_myfftshift', PACKAGE = 'spatialwarnings', mat)
}

randn <- function(min, max) {
    .Call('spatialwarnings_randn', PACKAGE = 'spatialwarnings', min, max)
}

shuffle_and_compute <- function(mat, indic, do_coarse_grain, subsize, nrep) {
    .Call('spatialwarnings_shuffle_and_compute', PACKAGE = 'spatialwarnings', mat, indic, do_coarse_grain, subsize, nrep)
}

normalize <- function(aspectr2D, dists, n0x, n0y) {
    .Call('spatialwarnings_normalize', PACKAGE = 'spatialwarnings', aspectr2D, dists, n0x, n0y)
}

get_distances <- function(nr, nc, n0x, n0y) {
    .Call('spatialwarnings_get_distances', PACKAGE = 'spatialwarnings', nr, nc, n0x, n0y)
}

get_rspectr <- function(ray, step, dists, aspectr2D) {
    .Call('spatialwarnings_get_rspectr', PACKAGE = 'spatialwarnings', ray, step, dists, aspectr2D)
}

