# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coarse_grain_cpp <- function(mat, subsize) {
    .Call('spatialwarnings_coarse_grain_cpp', PACKAGE = 'spatialwarnings', mat, subsize)
}

discpowerexp_norm <- function(expo, rate, xmin) {
    .Call('spatialwarnings_discpowerexp_norm', PACKAGE = 'spatialwarnings', expo, rate, xmin)
}

label_cpp <- function(mat, nbmask, wrap) {
    .Call('spatialwarnings_label_cpp', PACKAGE = 'spatialwarnings', mat, nbmask, wrap)
}

#' 
#' @title Compute the Moran's I at lag 1
#' 
#' @param mat A matrix
#' 
#' @description This function computes the Moran'I value at lag 1.
#'
#' @details See \link{indicator_moran} or \link{generic_spews} 
#'   for more information
#'
#' @return The Moran's I numeric value as a numeric number.
#' 
#' @seealso \link{indicator_moran}, \link{generic_spews} 
#' 
#' @export
raw_moran <- function(mat) {
    .Call('spatialwarnings_raw_moran', PACKAGE = 'spatialwarnings', mat)
}

tplsum <- function(expo, rate, xs, xmin) {
    .Call('spatialwarnings_tplsum', PACKAGE = 'spatialwarnings', expo, rate, xs, xmin)
}

shuffle_and_compute <- function(mat, indic, nrep, nthreads) {
    .Call('spatialwarnings_shuffle_and_compute', PACKAGE = 'spatialwarnings', mat, indic, nrep, nthreads)
}

rspectrum <- function(amat) {
    .Call('spatialwarnings_rspectrum', PACKAGE = 'spatialwarnings', amat)
}

#' 
#' @title Skewness
#' 
#' @description Compute the skewness of a given set of values 
#' 
#' @param X A vector of values
#' 
#' @seealso \code{\link[moments]{skewness}}
#' 
#'@export
raw_skewness <- function(X) {
    .Call('spatialwarnings_raw_skewness', PACKAGE = 'spatialwarnings', X)
}

sum_all_one_over_k <- function(from, to, expo) {
    .Call('spatialwarnings_sum_all_one_over_k', PACKAGE = 'spatialwarnings', from, to, expo)
}

sum_all_one_over_k_before <- function(n, expo) {
    .Call('spatialwarnings_sum_all_one_over_k_before', PACKAGE = 'spatialwarnings', n, expo)
}

