# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.coarse_grain_unsafe <- function(mat, subsize) {
    .Call('spatialwarnings_coarse_grain', PACKAGE = 'spatialwarnings', mat, subsize)
}

.get_nb_coords <- function(mat, X, nbmask, wrap) {
    .Call('spatialwarnings_get_nb_coords', PACKAGE = 'spatialwarnings', mat, X, nbmask, wrap)
}

.get_nb_values <- function(mat, X, nbmask, wrap) {
    .Call('spatialwarnings_get_nb_values', PACKAGE = 'spatialwarnings', mat, X, nbmask, wrap)
}

.label <- function(mat, nbmask, wrap) {
    .Call('spatialwarnings_label', PACKAGE = 'spatialwarnings', mat, nbmask, wrap)
}

#' @export
raw_moran <- function(mat) {
    .Call('spatialwarnings_raw_moran', PACKAGE = 'spatialwarnings', mat)
}

rspectrum <- function(rmat) {
    .Call('spatialwarnings_rspectrum', PACKAGE = 'spatialwarnings', rmat)
}

